# proof of concept for bulk download

name: poc_test

on:
  # push:
  #   branches: ['hk/bulk_download_0_spike']
  # pull_request:
  #   branches: [ "main" ]
  # schedule:
  #   # at 0 min after each hour (note this does not include update at 0 min after each hour
  #   #   since that job will be running in parallel to this)
  #   - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'debug'
jobs:
  generate-name:
    environment: test
    runs-on: ubuntu-latest
    outputs:
      v_current_run_timestamp: ${{ steps.get-timestamp.outputs.out }}
    steps:
      - name: generate-name
        id: get-timestamp
        run: echo "out=$(date '+%Y-%m-%d_%H%M_UTC')" >> $GITHUB_OUTPUT
  create_artifacts:
    needs: generate-name
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: clone cves
        uses: actions/checkout@v3
      - name: tag repository
        run: |
          git tag cve_${{ needs.generate-name.outputs.v_current_run_timestamp }}
          git push origin cve_${{ needs.generate-name.outputs.v_current_run_timestamp }}
      - name: build cves for zip download
        run: |
          pwd
          ls -al
          zip -r cves.zip ./review_set -x "*/\.*"
          # do a subset
          # zip -r cves1999.zip ./review_set/1999 -x "*/\.*"

      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: cves_${{ needs.generate-name.outputs.v_current_run_timestamp }}.zip
          path: ./cves.zip

  create_release:
    needs: [generate-name, create_artifacts]
    environment: test
    runs-on: ubuntu-latest
    steps:
      # - name: generate release
      #   run: |
      #     gh release create cves_${{ needs.generate-name.outputs.v_current_run_timestamp }}
      #     gh release create cves_${{ needs.generate-name.outputs.v_current_run_timestamp }} --title "CVEs on ${{ needs.generate-name.outputs.v_current_run_timestamp }}" --notes "this is a release of the latest CVEs as of ${{ needs.generate-name.outputs.v_current_run_timestamp }}." --latest

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cve_${{ needs.generate-name.outputs.v_current_run_timestamp }}
          release_name: CVE Release ${{ needs.generate-name.outputs.v_current_run_timestamp }}
          draft: false
          prerelease: false
          make_latest: true

  test_capabilities:
    needs: generate-name
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Test Environment Secret
        run: |
          echo '${{secrets.TEST_ENVIRONMENT_VAR}}'

      - name: Test REST API
        run: |
          # curl --location --request GET '${{secrets.CVE_API_HOST}}/cve?time_modified.gt=2022-12-10T00:00:00' \
          #  --header 'CVE-API-ORG: mitre' \
          #  --header 'CVE-API-USER: ${{secrets.CVE_API_USER}}' \
          #  --header 'CVE-API-KEY: ${{secrets.CVE_API_KEY}}' \
          #  --header 'Content-Type: application/json'
          curl https://raw.githubusercontent.com/CVEProject/cvelist/master/1999/0xxx/CVE-1999-0001.json
