# Github Action for tweeting newly published CVEs

name: Tweet New CVEs
on:
  # run every 5~10 minutes (min Github scheduling allowed)
  # note this may not complete when the hourly "CVE Release" workflow starts,
  #   so that the updates in this task may not be reflected
  #   in the CVE Release artifacts running in a separate workflow
  # note also that if this job runs longer than 5 minutes,
  #   the next job will run 5 minutes after this completes
  #  schedule:
  #  - cron: '*/5 * * * *'
  # Enables manual runs of this workflow from the Actions tab
  workflow_dispatch:
    inputs:
      params:
        description: 'command line arguments to update'
        required: false
        default: ''
jobs:
  tweet:
    environment: development
    runs-on: ubuntu-latest
    env:
      CVE_SERVICES_URL: https://cveawg.mitre.org
      CVES_BASE_DIRECTORY: cves
      CVES_RECENT_ACTIVITIES_FILENAME: recent_activities.json
      CVES_DEFAULT_UPDATE_LOOKBACK_IN_MINS: 180
      TWITTER_JSON_KEEP_MINS: 600
      CVE_API_ORG: ${{secrets.CVE_API_ORG}}
      CVE_API_USER: ${{secrets.CVE_API_USER}}
      CVE_API_KEY: ${{secrets.CVE_API_KEY}}
      TWITTER_APP_KEY: ${{secrets.TWITTER_APP_KEY}}
      TWITTER_APP_SECRET: ${{secrets.TWITTER_APP_SECRET}}
      TWITTER_ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
      TWITTER_ACCESS_SECRET: ${{secrets.TWITTER_ACCESS_SECRET}}
    # outputs:
    #   v_current_run_timestamp: ${{ steps.get-timestamp.outputs.out }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Download artifact from baseline workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          name: twitter_log.json
          path: ./twitter_log.json
          workflow_conclusion: success
          if_no_artifact_found: ignore          
          
      - name: tweet
        run: |
          node ./.github/workflows/dist/index.js twitter ${{ github.event.inputs.params }}
          
          
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: twitter_log.json
          path: ./twitter_log.json
          
          
      - name: output
        uses: actions/github-script@v6
        with:
          script: |
              core.notice("this is a notice")
